### ISSUE TITLE
`controlWrite` packets incorrectly return no data for windows pcaps

### ISSUE THREAD

**Issue by bahorn** [JohnDMcMaster/usbrply#60]
## Issue
When I tested this [pcap](https://gitlab.com/CalcProgrammer1/OpenRGB/uploads/0d86c98a690eb119d7cf022a729b4546/Static_Red.pcapng) (and a few others) by running:
```
usbrply ~/Downloads/Static_Red.pcapng -j
```
The resulting JSON (and generated code) just had an empty string for the data attribute in each packet for `controlWrite`, which isn't correct for this capture.

I've tested this against the latest master and the winsleep branch on both Ubuntu Linux and Windows 10. This only occurs on pcaps going through win-pcap, as my usbmon captures all work perfectly.
All the pcaps I've tested were taken from the OpenRGB issue tracker and are from Windows 10 users, captured using fairly recent builds of Wireshark.

## Root Cause

Seems the comment at the top of `win-pcap.py` is no longer the case, at least for the captures I've found:
> -Control write has the request on the response packet

As when I checked with verbose mode, I found the full request already there (unless I misunderstood something).

So currently it returns the data from the response, after skipping the first byte, which ends up being an empty string.

## Workaround

I've patched this for myself by just copying over `processControlCompleteOut` from `lin_pcap.py` into `win_pcap.py`, but I gather that there are older pcaps that this fix won't work for, so it isn't the ideal solution.

**Comment by JohnDMcMaster** [comment]
Thanks for submitting your detailed report and being patient as I got to this! Yeah agree there might be a pcap compatibility issue but I've merged your fix for now and I'll revisit those as they come back up. I've also added a fix and improved the test cases (https://github.com/JohnDMcMaster/usbrply/blob/master/test/test_misc.py#L148) which should help if/when the other pcap format comes back up.
